# Generated by Django 5.0.1 on 2025-11-20 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipeatendimento',
            name='area_de_negocio',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='area_de_negocio',
        ),
        migrations.RemoveField(
            model_name='contatocliente',
            name='proprietario',
        ),
        migrations.RemoveField(
            model_name='contatocliente',
            name='unidade_de_negocio',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='equipe_atendimento',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='fraudante_utilizou_ia',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='resposta_da_area',
        ),
        migrations.RemoveField(
            model_name='unidadedenegocio',
            name='contato',
        ),
        migrations.RemoveField(
            model_name='unidadedenegocio',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='unidadedenegocio',
            name='email_de_contato',
        ),
        migrations.RemoveField(
            model_name='unidadedenegocio',
            name='proprietario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='gerente',
        ),
        migrations.DeleteModel(
            name='AreaNegocio',
        ),
        migrations.DeleteModel(
            name='ContatoCliente',
        ),
        migrations.DeleteModel(
            name='EquipeAtendimento',
        ),
    ]
