# Generated by Django 5.0.1 on 2025-11-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_equipeatendimento_area_de_negocio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='fraudante_utilizou_ia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='tipo_fraude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='unidadedenegocio',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unidadedenegocio',
            name='nome',
            field=models.CharField(default='Unidade Padrão', max_length=255),
        ),
    ]
