# Generated by Django 5.0.1 on 2025-11-26 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_ocorrencia_data_nascimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
